export const data = [
  {
    id: 1,
    firstName: 'Jean',
    lastName: 'Dupond',
    startDate: '01/01/2021',
    department: 'Engeenering',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 2,
    firstName: 'Pierre',
    lastName: 'Martin',
    startDate: '01/01/2021',
    department: 'Sales',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 3,
    firstName: 'Paul',
    lastName: 'Durand',
    startDate: '01/01/2021',
    department: 'Human Resources',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 4,
    firstName: 'Jacques',
    lastName: 'Lefevre',
    startDate: '01/01/2021',
    department: 'Human Resources',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 5,
    firstName: 'Marie',
    lastName: 'Lemoine',
    startDate: '01/01/2021',
    department: 'IT',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 6,
    firstName: 'Sophie',
    lastName: 'Leroy',
    startDate: '01/01/2021',
    department: 'IT',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 7,
    firstName: 'Lucie',
    lastName: 'Lacour',
    startDate: '01/01/2021',
    department: 'IT',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 8,
    firstName: 'Julie',
    lastName: 'Lefevre',
    startDate: '01/01/2021',
    department: 'IT',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 9,
    firstName: 'Camille',
    lastName: 'Lemoine',
    startDate: '01/01/2021',
    department: 'IT',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 10,
    firstName: 'Marie',
    lastName: 'Lemoine',
    startDate: '01/01/2021',
    department: 'IT',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 11,
    firstName: 'Sophie',
    lastName: 'Leroy',
    startDate: '01/01/2021',
    department: 'IT',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 12,
    firstName: 'Lucie',
    lastName: 'Lacour',
    startDate: '01/01/2021',
    department: 'IT',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 13,
    firstName: 'Julie',
    lastName: 'Lefevre',
    startDate: '01/01/2021',
    department: 'IT',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 14,
    firstName: 'Camille',
    lastName: 'Lemoine',
    startDate: '01/01/2021',
    department: 'IT',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
  {
    id: 15,
    firstName: 'Marie',
    lastName: 'Lemoine',
    startDate: '01/01/2021',
    department: 'IT',
    dateOfBirth: '01/01/1990',
    street: '1 rue de la Paix',
    city: 'Paris',
    state: 'FR',
    zip: '75000',
  },
]
